---
## Example blueprint playbook
- hosts: localhost
  roles:
    # Copy clean blueprint to /tmp/blueprint.json 
    # Generate hostgroups with components
    # Register handlers
    - build-blueprint 
    # Complete blueprint configurations by calling required roles
    - blueprint-hdfs
    - blueprint-yarn
